# Spell checker configuration
# See: https://github.com/crate-ci/typos

[default]
extend-ignore-re = [
    # alls-green GitHub Action (re-actors/alls-green)
    "alls-green",
]

[files]
# Files to ignore
# extend-exclude = []
