# Spell checker configuration
# See: https://github.com/crate-ci/typos

[default]
extend-ignore-re = [
    # alls-green GitHub Action (re-actors/alls-green)
    "alls-green",
]

[default.extend-words]
# Theta-Rho file extension (.thr) used throughout the project
thr = "thr"

[files]
# Files to ignore
# extend-exclude = []
